In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

## Dataset

Complet dataset

In [ ]:
dataset_path = "dataset/"
film_data_path = dataset_path + "films.csv"
films = pd.read_csv(film_data_path)
films

Target film: The Imitation Game

In [ ]:
target_film = films.loc[films["Film"] == "The Imitation Game"]
target_film

Other films

In [ ]:
new_films = films.loc[films["Film"] != "The Imitation Game"]
new_films

In [ ]:
new_films_values = new_films.drop("Film", axis=1)
new_films_values = new_films_values.values
new_films_values

In [ ]:
target_film_values = target_film.drop("Film", axis=1)
target_film_values = target_film_values.values
target_film_values

In [ ]:
euclidean_distances = np.linalg.norm(new_films_values - target_film_values, axis=1)
euclidean_distances

In [ ]:
def manhattan_distance(a, b):
    return np.array(list(map(np.sum,np.array(list(map(np.abs, a - b))))))
    
manhattan_distances = manhattan_distance(new_films_values, target_film_values[0])
manhattan_distances

In [ ]:
k = 6
euclidean_nearest_neighbor_ids = euclidean_distances.argsort()[:k]
euclidean_nearest_neighbor_ids

In [ ]:
k = 6
manhattan_nearest_neighbor_ids = manhattan_distances.argsort()[:k]
manhattan_nearest_neighbor_ids

In [ ]:
new_film_euclidean = new_films.copy()
new_film_euclidean.insert(len(new_film_euclidean.columns), "Euklidsko rastojanje", euclidean_distances)
new_film_euclidean.sort_values(by=["Euklidsko rastojanje"], ascending=False)

In [ ]:
new_film_manhattan = new_films.copy()
new_film_manhattan.insert(len(new_film_manhattan.columns), "Menhetn rastojanje", manhattan_distances)
new_film_manhattan.sort_values(by=["Menhetn rastojanje"], ascending=False)

Normalization

In [ ]:
imdb_min = np.min(films["IMDB"].values)
imdb_max = np.max(films["IMDB"].values)
print(imdb_min, imdb_max)


In [ ]:
target_film_imdb_values_normalized = target_film["IMDB"].values
target_film_imdb_values_normalized = (target_film_imdb_values_normalized - imdb_min) / (imdb_max - imdb_min)
target_film_imdb_values_normalized

In [321]:
new_films_imdb_values_normalized = new_films["IMDB"].values
new_films_imdb_values_normalized = (new_films_imdb_values_normalized - imdb_min) / (imdb_max - imdb_min)
new_films_imdb_values_normalized

array([0.62068966, 0.79310345, 0.82758621, 1.        , 0.31034483,
       0.5862069 , 0.        , 0.68965517, 0.79310345, 0.51724138,
       0.93103448, 0.65517241])

In [322]:
new_films_normalized = new_films.drop("IMDB", axis=1)
new_films_normalized.insert(1, "IMDB", new_films_imdb_values_normalized)
new_films_normalized

Film      IMDB  Biografski  Drama  Triler  Komedija  \
1                Ex Machina  0.620690           0      1       0         0   
2          A Beautiful Mind  0.793103           1      1       0         0   
3         Good Will Hunting  0.827586           0      1       0         0   
4              Forrest Gump  1.000000           0      1       0         0   
5                        21  0.310345           0      1       0         0   
6                    Gifted  0.586207           0      1       0         0   
7       Travelling Salesman  0.000000           0      1       0         0   
8                    Avatar  0.689655           0      0       0         0   
9   The Wolf of Wall Street  0.793103           1      0       0         1   
10           A Time To Kill  0.517241           0      1       1         0   
11             Interstellar  0.931034           0      1       0         0   
12           The Wind Rises  0.655172           1      1       0         0   

    Misterija  
1           1  
2           0  
3           0  
4           0  
5           0  
6           0  
7           1  
8           0  
9           0  
10          0  
11          0  
12          0

In [323]:
target_film_normalized = target_film.drop("IMDB", axis=1)
target_film_normalized.insert(1, "IMDB", target_film_imdb_values_normalized)
target_film_normalized

Film      IMDB  Biografski  Drama  Triler  Komedija  \
0  The Imitation Game  0.724138           1      1       1         0   

   Misterija  
0          0

In [329]:
new_films_values_normalized = new_films_normalized.drop("Film", axis=1)
new_films_values_normalized = new_films_normalized.values
new_films_values_normalized

array([['Ex Machina', 0.6206896551724137, 0, 1, 0, 0, 1],
       ['A Beautiful Mind', 0.7931034482758617, 1, 1, 0, 0, 0],
       ['Good Will Hunting', 0.8275862068965517, 0, 1, 0, 0, 0],
       ['Forrest Gump', 1.0, 0, 1, 0, 0, 0],
       ['21', 0.3103448275862067, 0, 1, 0, 0, 0],
       ['Gifted', 0.5862068965517239, 0, 1, 0, 0, 0],
       ['Travelling Salesman', 0.0, 0, 1, 0, 0, 1],
       ['Avatar', 0.689655172413793, 0, 0, 0, 0, 0],
       ['The Wolf of Wall Street', 0.7931034482758617, 1, 0, 0, 1, 0],
       ['A Time To Kill', 0.5172413793103448, 0, 1, 1, 0, 0],
       ['Interstellar', 0.9310344827586203, 0, 1, 0, 0, 0],
       ['The Wind Rises', 0.6551724137931032, 1, 1, 0, 0, 0]],
      dtype=object)

In [ ]:
target_film_values_normalized = target_film_normalized.drop("Film", axis=1)
target_film_values_normalized = target_film_normalized.values


In [327]:
euclidean_distances_normalized = np.linalg.norm(new_films_values_normalized - target_film_values_normalized, axis=1)
euclidean_distances_normalized

manhattan_distances_normalized = manhattan_distance(new_films_values_normalized, target_film_values_normalized[0])
manhattan_distances_normalized


TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [314]:
k = 6
euclidean_nearest_neighbor_normalized_ids = euclidean_distances_normalized.argsort()[:k]
euclidean_nearest_neighbor_normalized_ids


array([ 1, 11,  9,  2,  5, 10], dtype=int64)

In [315]:
k = 6
manhattan_nearest_neighbor_normalized_ids = manhattan_distances_normalized.argsort()[:k]
manhattan_nearest_neighbor_normalized_ids

array([ 1, 11,  9,  2,  5, 10], dtype=int64)

In [ ]:
new_film_euclidean = new_films.copy()
new_film_euclidean.insert(len(new_film_euclidean.columns), "Euklidsko rastojanje", euclidean_distances)
new_film_euclidean.sort_values(by=["Euklidsko rastojanje"], ascending=False)

In [ ]:
new_film_manhattan = new_films.copy()
new_film_manhattan.insert(len(new_film_manhattan.columns), "Menhetn rastojanje", manhattan_distances)
new_film_manhattan.sort_values(by=["Menhetn rastojanje"], ascending=False)