In [222]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [223]:
dataset_path = "dataset/"
film_data_path = dataset_path + "films.csv"
films = pd.read_csv(film_data_path)

In [224]:
target_film = films.loc[films["Film"] == "The Imitation Game"]
target_film

Film  IMDB  Biografski  Drama  Triler  Komedija  Misterija
0  The Imitation Game   8.0           1      1       1         0          0

In [225]:
new_films = films.loc[films["Film"] != "The Imitation Game"]
new_films

Film  IMDB  Biografski  Drama  Triler  Komedija  \
1                Ex Machina   7.7           0      1       0         0   
2          A Beautiful Mind   8.2           1      1       0         0   
3         Good Will Hunting   8.3           0      1       0         0   
4              Forrest Gump   8.8           0      1       0         0   
5                        21   6.8           0      1       0         0   
6                    Gifted   7.6           0      1       0         0   
7       Travelling Salesman   5.9           0      1       0         0   
8                    Avatar   7.9           0      0       0         0   
9   The Wolf of Wall Street   8.2           1      0       0         1   
10           A Time To Kill   7.4           0      1       1         0   
11             Interstellar   8.6           0      1       0         0   
12           The Wind Rises   7.8           1      1       0         0   

    Misterija  
1           1  
2           0  
3           0  
4           0  
5           0  
6           0  
7           1  
8           0  
9           0  
10          0  
11          0  
12          0

In [226]:
new_films_values = new_films.drop("Film", axis=1)
new_films_values = new_films_values.values
new_films_values

array([[7.7, 0. , 1. , 0. , 0. , 1. ],
       [8.2, 1. , 1. , 0. , 0. , 0. ],
       [8.3, 0. , 1. , 0. , 0. , 0. ],
       [8.8, 0. , 1. , 0. , 0. , 0. ],
       [6.8, 0. , 1. , 0. , 0. , 0. ],
       [7.6, 0. , 1. , 0. , 0. , 0. ],
       [5.9, 0. , 1. , 0. , 0. , 1. ],
       [7.9, 0. , 0. , 0. , 0. , 0. ],
       [8.2, 1. , 0. , 0. , 1. , 0. ],
       [7.4, 0. , 1. , 1. , 0. , 0. ],
       [8.6, 0. , 1. , 0. , 0. , 0. ],
       [7.8, 1. , 1. , 0. , 0. , 0. ]])

In [227]:
target_film_values = target_film.drop("Film", axis=1)
target_film_values = target_film_values.values
target_film_values

array([[8., 1., 1., 1., 0., 0.]])

In [228]:
euclidean_distances = np.linalg.norm(new_films_values - target_film_values, axis=1)
euclidean_distances

array([1.75783958, 1.0198039 , 1.44568323, 1.62480768, 1.8547237 ,
       1.46969385, 2.72213152, 1.73493516, 1.74355958, 1.16619038,
       1.53622915, 1.0198039 ])

In [229]:
def manhattan_distance(a, b):
    return np.array(list(map(np.sum,np.array(list(map(np.abs, a - b))))))
    
manhattan_distances = manhattan_distance(new_films_values, target_film_values[0])
manhattan_distances

array([3.3, 1.2, 2.3, 2.8, 3.2, 2.4, 5.1, 3.1, 3.2, 1.6, 2.6, 1.2])

In [230]:
k = 6
euclidean_nearest_neighbor_ids = euclidean_distances.argsort()[:k]
euclidean_nearest_neighbor_ids

array([ 1, 11,  9,  2,  5, 10], dtype=int64)

In [231]:
k = 6
manhattan_nearest_neighbor_ids = manhattan_distances.argsort()[:k]
manhattan_nearest_neighbor_ids

array([ 1, 11,  9,  2,  5, 10], dtype=int64)

In [239]:
new_film_euclidean = new_films.copy()
new_film_euclidean.insert(len(new_film_euclidean.columns), "Euklidsko rastojanje", euclidean_distances)
new_film_euclidean.sort_values(by=["Euklidsko rastojanje"], ascending=False)

Film  IMDB  Biografski  Drama  Triler  Komedija  \
7       Travelling Salesman   5.9           0      1       0         0   
5                        21   6.8           0      1       0         0   
1                Ex Machina   7.7           0      1       0         0   
9   The Wolf of Wall Street   8.2           1      0       0         1   
8                    Avatar   7.9           0      0       0         0   
4              Forrest Gump   8.8           0      1       0         0   
11             Interstellar   8.6           0      1       0         0   
6                    Gifted   7.6           0      1       0         0   
3         Good Will Hunting   8.3           0      1       0         0   
10           A Time To Kill   7.4           0      1       1         0   
12           The Wind Rises   7.8           1      1       0         0   
2          A Beautiful Mind   8.2           1      1       0         0   

    Misterija  Euklidsko rastojanje  
7           1              2.722132  
5           0              1.854724  
1           1              1.757840  
9           0              1.743560  
8           0              1.734935  
4           0              1.624808  
11          0              1.536229  
6           0              1.469694  
3           0              1.445683  
10          0              1.166190  
12          0              1.019804  
2           0              1.019804

In [241]:
new_film_manhattan = new_films.copy()
new_film_manhattan.insert(len(new_film_manhattan.columns), "Menhetn rastojanje", manhattan_distances)
new_film_manhattan.sort_values(by=["Menhetn rastojanje"], ascending=False)

Film  IMDB  Biografski  Drama  Triler  Komedija  \
7       Travelling Salesman   5.9           0      1       0         0   
1                Ex Machina   7.7           0      1       0         0   
5                        21   6.8           0      1       0         0   
9   The Wolf of Wall Street   8.2           1      0       0         1   
8                    Avatar   7.9           0      0       0         0   
4              Forrest Gump   8.8           0      1       0         0   
11             Interstellar   8.6           0      1       0         0   
6                    Gifted   7.6           0      1       0         0   
3         Good Will Hunting   8.3           0      1       0         0   
10           A Time To Kill   7.4           0      1       1         0   
12           The Wind Rises   7.8           1      1       0         0   
2          A Beautiful Mind   8.2           1      1       0         0   

    Misterija  Menhetn rastojanje  
7           1                 5.1  
1           1                 3.3  
5           0                 3.2  
9           0                 3.2  
8           0                 3.1  
4           0                 2.8  
11          0                 2.6  
6           0                 2.4  
3           0                 2.3  
10          0                 1.6  
12          0                 1.2  
2           0                 1.2

Normalization

In [242]:
new_films_values_normalized = new_films.drop("Film", axis=1)
new_films_values_normalized = new_films_values_normalized.values
new_films_values_normalized = \
    new_films_values_normalized - np.min(new_films_values_normalized) / \
    np.max(new_films_values_normalized) - np.min(new_films_values_normalized)

array([[7.7, 0. , 1. , 0. , 0. , 1. ],
       [8.2, 1. , 1. , 0. , 0. , 0. ],
       [8.3, 0. , 1. , 0. , 0. , 0. ],
       [8.8, 0. , 1. , 0. , 0. , 0. ],
       [6.8, 0. , 1. , 0. , 0. , 0. ],
       [7.6, 0. , 1. , 0. , 0. , 0. ],
       [5.9, 0. , 1. , 0. , 0. , 1. ],
       [7.9, 0. , 0. , 0. , 0. , 0. ],
       [8.2, 1. , 0. , 0. , 1. , 0. ],
       [7.4, 0. , 1. , 1. , 0. , 0. ],
       [8.6, 0. , 1. , 0. , 0. , 0. ],
       [7.8, 1. , 1. , 0. , 0. , 0. ]])